### ISSUE TITLE
Lessson 5. Task 3. WeekDays

### ISSUE THREAD

**Issue by milkina** [Nastya89/courses#4]
1. else if ((tempValue == 2)) - лишние скобки. Можно просто
else if (tempValue == 2)
2.  Вместо 
          else if ((tempValue == 6)) {
                System.out.println("Выходной");
            } else if ((tempValue == 7)) {
                System.out.println("Выходной");
            } 
лучше писать так:
           else if (tempValue == 6 || tempValue == 7) {
                System.out.println("Выходной");
            }

**Comment by Nastya89** [comment]
Done
